app/containers/InterventionDetailsPage/components/InterventionStatusButtons/CsvButtons.js
app/containers/InterventionDetailsPage/components/InterventionStatusButtons/index.js
app/containers/InterventionDetailsPage/index.js
app/containers/Navbar/components/InterventionsNavbar.js
app/containers/SelectResearchers/index.js
app/containers/SettingsPanel/containers/ConversationsTranscriptPanel.tsx
app/containers/SettingsPanel/index.tsx
app/containers/SingleTile/index.js
app/global/reducers/intervention/selectors.js

- [CIAS-3426](https://htdevelopers.atlassian.net/browse/CIAS30-3426)
- as title
- remove filtering out current user from fetched researchers (moved to BE)
https://github.com/Michigan-State-University/cias-web/assets/86963976/cda39546-dff9-46aa-a1fb-bc98ed1fd72d

[CIAS30-3426] Show participants data to users with access only

---

app/containers/InterventionDetailsPage/Header.js
app/containers/InterventionDetailsPage/components/InterventionStatusButtons/CsvButtons.js
app/containers/InterventionDetailsPage/components/InterventionStatusButtons/index.js
app/containers/InterventionDetailsPage/index.js
app/containers/SettingsPanel/containers/ConversationsTranscriptPanel.tsx
app/containers/SettingsPanel/index.tsx
app/global/reducers/intervention/actions.js
app/global/reducers/intervention/reducer.js
app/models/Intervention/Intervention.ts
app/utils/useNotificationChannel/useNotificationChannel.ts

- [CIAS-3442](https://htdevelopers.atlassian.net/browse/CIAS30-3442)
- Fetch CSV report and conversations transcript from a separate
https://github.com/Michigan-State-University/cias-web/assets/86963976/c857925d-54cd-471d-a13c-166082200549
secure endpoint

[CIAS30-3442] Fetch protected attachments form separate endpoints

---

app/containers/AnswerSessionPage/index.js

- [CIAS-3348](https://htdevelopers.atlassian.net/browse/CIAS30-3348)
- Fix the numeric min/max setting not applying if question is not required
N/A

[CIAS-3348] - Fix required-numeric-setting

---

app/containers/SingleTile/index.js

- [CIAS-3450](https://htdevelopers.atlassian.net/browse/CIAS30-3450)
- Show collaborating intervention icon if the intervention has any collaborators
N/A

[CIAS30-3450] Show that intervention has collaborators

---

app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/SingleCollaboratorRow.tsx
app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/index.tsx
app/containers/InterventionDetailsPage/index.js
app/containers/SingleTile/index.js

- [CIAS-3452](https://htdevelopers.atlassian.net/browse/CIAS30-3452)
- as title
N/A

[CIAS30-3452] Allow only intervention owner to grant data access

---

app/containers/AnswerSessionPage/index.js

- [CIAS-3448](https://htdevelopers.atlassian.net/browse/CIAS30-3448)
- Allow empty answers in numeric questions
N/A

[CIAS-3448] - Allow empty answer in numeric question

---

app/models/Intervention/Intervention.ts

- [CIAS-3419](https://htdevelopers.atlassian.net/browse/CIAS30-3419)
- Add missing field to simple intervention interface
N/A

[CIAS-3419] - Add missing field to simple intervention interface

---

app/containers/InterventionDetailsPage/index.js
app/containers/InterventionDetailsPage/messages.js
app/containers/Sessions/containers/EditSessionPage/EditClassicSession.tsx
app/containers/ShareExternallyModal/index.ts
app/containers/ShareExternallyModal/messages.ts
app/containers/ShareExternallyModal/types.ts
app/containers/ShareExternallyModal/useShareExternallyModal.tsx
app/containers/SingleTile/index.js
app/containers/SingleTile/messages.js

- [CIAS-3451](https://htdevelopers.atlassian.net/browse/CIAS30-3451)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/3cec9dba-916a-4bcf-b87e-e460597803ba

[CIAS30-3451] Add feature descriptions to modals

---

app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/index.tsx
app/containers/InterventionDetailsPage/index.js
app/containers/SingleTile/index.js

- [CIAS-3480](https://htdevelopers.atlassian.net/browse/CIAS30-3480)
- as title
N/A

[CIAS30-3480] Exclude intervention owner from collaborators modal

---

README.md

Slight modifications to description of features and how to access.
- 
N/A

Update to README.md by Steve

---

.github/ISSUE_TEMPLATE/bug_report.md
CONTRIBUTING.md
README.md
package.json

- [CIAS-3486](https://htdevelopers.atlassian.net/browse/CIAS30-3486)
- as title
N/A

[CIAS30-3486] Update repo links in documentation

---

app/containers/Navbar/components/InterventionsNavbar.js

- [CIAS-3491](https://htdevelopers.atlassian.net/browse/CIAS30-3491)
- as title

[CIAS30-3491] Disable session name input when editing disabled

---

app/containers/AnswerSessionPage/saga.js

- [CIAS-3503](https://htdevelopers.atlassian.net/browse/CIAS30-3503)
- fix import
N/A

[CIAS30-3503] Fix import

---

app/components/FormikApiSelect/FormikApiSelect.tsx
app/components/FormikApiSelect/index.ts
app/components/FormikSwitchInput/index.tsx
app/components/Select/ApiSelect.js
app/components/Select/components.js
app/components/Select/index.js
app/components/Select/messages.js
app/containers/AnswerSessionPage/layouts/HenryFordInitialScreenLayout.tsx
app/containers/AnswerSessionPage/layouts/messages.ts
app/containers/AnswerSessionPage/saga.js
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/HfHsAccessModalUI.tsx
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/ThirdPartyToolsAccessModal.tsx
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/constants.ts
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/messages.ts
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/types.ts
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/utils.ts
app/containers/Sessions/containers/EditSessionPage/EditCatSession.tsx
app/containers/SingleTile/tests/__snapshots__/index.test.js.snap
app/global/reducers/intervention/reducer.js
app/models/Intervention/ClinicLocation.ts
app/models/Intervention/Intervention.ts
app/models/Intervention/index.ts
app/utils/useGet.ts

- [CIAS-3514](https://htdevelopers.atlassian.net/browse/CIAS30-3514)
- as title
- send session_id when verifying patient data
- display BE error message when verification fails
https://github.com/Michigan-State-University/cias-web/assets/86963976/5d0f6221-dec3-4a16-91cd-fcd6e0221fea

[CIAS30-3514] Add clinic locations select to HFHS settings

---

app/components/MissingAnimationsModal/SingleAnimationRow.tsx
app/components/Select/PopularOptionsSelect.tsx
app/containers/AnswerSessionPage/layouts/HenryFordInitialScreenLayout.tsx
app/containers/InterventionDetailsPage/components/Modals/InterventionSettingsModal/index.tsx
app/containers/InterventionPage/ShareFilter.tsx
app/containers/Sessions/components/NarratorConflictModal/index.tsx
app/containers/Sessions/components/QuestionSettings/Settings/Components/Blocks/Reflections/ReflectionBlock.tsx
app/containers/Sessions/containers/EditSessionPage/EditCatSession.tsx
app/containers/Sessions/containers/TextMessagesPage/components/ParticipantPersonalData/ParticipantPersonalData.tsx
app/containers/TranslateInterventionModal/components/TranslateVoiceSettings/index.tsx
app/global/constants/regex.js
app/global/i18n/globalMessages.js
app/utils/validators/index.js
app/utils/validators/stringValidators.ts

- [CIAS-3516](https://htdevelopers.atlassian.net/browse/CIAS30-3516)
- as title

[CIAS30-3516] Make HF first and last name validation stricter

---

app/global/i18n/globalMessages.js

- [CIAS-3521](https://htdevelopers.atlassian.net/browse/CIAS30-3521)
- as title

[CIAS30-3521] Change intervention filters copies

---

app/containers/AnswerSessionPage/components/tests/__snapshots__/NumberQuestion.test.js.snap
app/containers/AnswerSessionPage/index.js
app/containers/AnswerSessionPage/layouts/NumberQuestionLayout.js
app/containers/Sessions/components/QuestionData/NumberQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionDetails/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionSettings/Settings/Components/Tabs/SettingsOption.js
app/containers/Sessions/components/QuestionSettings/Settings/Components/messages.js

- [CIAS-3519](https://htdevelopers.atlassian.net/browse/CIAS30-3519)
- Change min length input placeholder in number screen settings
- Show error when input value is invalid when answering question

[CIAS30-3519] Change min length input placeholder and show hint as error

---

app/components/FormikDatePicker/index.tsx
app/components/Input/ApprovableInput.js
app/components/Input/index.js
app/components/Input/tests/__snapshots__/index.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/CurrencyQuestion.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/DateQuestion.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/NumberQuestion.test.js.snap
app/containers/AnswerSessionPage/index.js
app/containers/AnswerSessionPage/layouts/HenryFordInitialScreenLayout.tsx
app/containers/AnswerSessionPage/layouts/NumberQuestionLayout.js
app/containers/AnswerSessionPage/layouts/messages.ts
app/containers/InterventionDetailsPage/components/SessionSchedule/tests/__snapshots__/exactDate.test.js.snap
app/containers/InterventionDetailsPage/index.js
app/containers/Sessions/components/QuestionData/DateQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionData/NumberQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionDetails/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionSettings/Settings/Components/Tabs/SettingsOption.js
app/containers/Sessions/components/QuestionSettings/Settings/Components/messages.js
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageScheduling/index.js
app/containers/ShareBox/Components/UserList.js
app/containers/ShareBox/NormalShareBox.tsx
app/containers/ShareBox/OrganizationShareBox.js
app/containers/ShareBox/styled.js
app/containers/ShareBox/tests/__snapshots__/index.test.js.snap
app/global/i18n/globalMessages.js

- [CIAS-3529](https://htdevelopers.atlassian.net/browse/CIAS30-3529)
- propagate dev to hf
- use native date input in formik datepicker
N/A

[CIAS30-3529] Propagate dev to hf and use native date input 

---

app/components/Input/ApprovableInput.js
app/components/Input/index.js
app/components/Input/tests/__snapshots__/index.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/CurrencyQuestion.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/DateQuestion.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/NumberQuestion.test.js.snap
app/containers/AnswerSessionPage/index.js
app/containers/AnswerSessionPage/layouts/NumberQuestionLayout.js
app/containers/InterventionDetailsPage/components/SessionSchedule/tests/__snapshots__/exactDate.test.js.snap
app/containers/InterventionDetailsPage/index.js
app/containers/Sessions/components/QuestionData/DateQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionData/NumberQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionDetails/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionSettings/Settings/Components/Tabs/SettingsOption.js
app/containers/Sessions/components/QuestionSettings/Settings/Components/messages.js
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageScheduling/index.js
app/containers/ShareBox/Components/UserList.js
app/containers/ShareBox/NormalShareBox.tsx
app/containers/ShareBox/OrganizationShareBox.js
app/containers/ShareBox/styled.js
app/containers/ShareBox/tests/__snapshots__/index.test.js.snap
app/global/i18n/globalMessages.js

DEV => TEST 25/08/2023

---

app/containers/App/tests/__snapshots__/index.test.js.snap
app/containers/InterventionDetailsPage/components/InterventionStatusButtons/tests/__snapshots__/index.test.js.snap
app/containers/InterventionPage/tests/__snapshots__/index.test.js.snap
app/global/reducers/auth/messages.js
app/models/Status/StatusTypes.js

DEV => TEST 25/08/2023 v2

---

app/containers/AnswerSessionPage/index.js
app/containers/UserInterventionPage/UserSessionTile.tsx
app/models/UserSession/UserSession.ts

- [CIAS-3511](https://htdevelopers.atlassian.net/browse/CIAS30-3511)
- as title
N/A

[CIAS30-3511] Check if user session is started by the "started" flag

---

app/components/Input/ApprovableInput.js
app/components/Input/index.js
app/components/Input/tests/__snapshots__/index.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/CurrencyQuestion.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/DateQuestion.test.js.snap
app/containers/InterventionDetailsPage/components/SessionSchedule/tests/__snapshots__/exactDate.test.js.snap
app/containers/Sessions/components/QuestionData/DateQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageScheduling/index.js

This reverts commit c9bfda1955662a65837a53809c0729083ad46f54 and PR https://github.com/Michigan-State-University/cias-web/pull/60

Revert "[CIAS30-3520] Use native date input in approvable input (#60)"

---

app/components/Input/ApprovableInput.js
app/components/Input/index.js
app/components/Input/tests/__snapshots__/index.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/CurrencyQuestion.test.js.snap
app/containers/AnswerSessionPage/components/tests/__snapshots__/DateQuestion.test.js.snap
app/containers/InterventionDetailsPage/components/SessionSchedule/tests/__snapshots__/exactDate.test.js.snap
app/containers/Sessions/components/QuestionData/DateQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageScheduling/index.js

DEV => TEST 27/07/2023

---

app/components/FormikDatePicker/index.tsx
app/containers/AnswerSessionPage/components/ApiErrorMessage.tsx
app/containers/AnswerSessionPage/layouts/HenryFordInitialScreenLayout.tsx
app/containers/AnswerSessionPage/layouts/messages.ts
app/containers/AnswerSessionPage/messages.js
app/containers/Sessions/components/QuestionData/HenryFordInitialScreen/index.tsx
app/models/HfhsPatient/HfhsPatient.ts

- [CIAS-3528](https://htdevelopers.atlassian.net/browse/CIAS30-3528)
- at title + update date input placeholder
https://github.com/Michigan-State-University/cias-web/assets/86963976/fe999bd8-caea-4775-9eba-5e299857056d

[CIAS30-3528] Add mrn input to Henry Ford Initial Screen

---

package-lock.json
package.json

- [CIAS-3548](https://htdevelopers.atlassian.net/browse/CIAS30-3548)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/0869842b-dd5b-4bc5-9c24-3729e2f00af3

[CIAS30-3548] Upgrade react-player package to support youtube shorts

---

app/containers/InterventionDetailsPage/components/Modals/InterventionSettingsModal/index.tsx
app/containers/InterventionDetailsPage/index.js
app/containers/SettingsPanel/containers/NavigatorSettingsModal.tsx
app/containers/SettingsPanel/index.tsx

Cherry pick [CIAS30-3552] from test to dev

Cherry pick [CIAS30-3552] from test to dev

---

app/containers/InterventionDetailsPage/components/Modals/InterventionSettingsModal/index.tsx
app/containers/InterventionDetailsPage/index.js
app/containers/SettingsPanel/containers/NavigatorSettingsModal.tsx
app/containers/SettingsPanel/index.tsx

TEST => MASTER 08/02/2023

---

app/components/HenryFordBrachingInfoModal/useHenryFordBranchingInfoModal.tsx
app/components/Modal/ConfirmationModal.tsx
app/components/Modal/tests/__snapshots__/ConfirmationModal.test.js.snap
app/containers/Sessions/components/QuestionListItem/index.js
app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/ReportTemplateMainSettings.js

DEV => TEST 18/08/2023

---

app/global/reducers/reportTemplates/sagas/messages.js
app/global/reducers/reportTemplates/sagas/updateReportTemplate.js

- [CIAS-3597](https://htdevelopers.atlassian.net/browse/CIAS30-3597)
- as title

[CIAS30-3597] Display error message when updating report template

---

app/containers/AnswerSessionPage/components/ThirdPartyQuestion.js
app/containers/AnswerSessionPage/layouts/ThirdPartyQuestionLayout.js
app/containers/SessionMapPage/components/QuestionDetails/VariablesAndScores/index.tsx
app/models/Answer/Answer.ts

- [CIAS-3604](https://htdevelopers.atlassian.net/browse/CIAS30-3604)
- send `var` and `numeric_value` when submitting answer to 3rd party report screen
- fix email being displayed instead of values in chips session map question details
N/A

[CIAS30-3604] Update answer body and fix session map chips

---

app/components/BaseComponentStyles/flex.js
app/components/FormikControlLayout/index.tsx
app/components/FormikInput/InputComponent.tsx
app/components/FormikInput/index.tsx
app/components/Input/index.js
app/components/Modal/useModal.tsx
app/containers/ClearInterventionData/ClearInterventionDataModalContent.tsx
app/containers/ClearInterventionData/constants.ts
app/containers/ClearInterventionData/messages.ts
app/containers/ClearInterventionData/types.ts
app/containers/ClearInterventionData/useClearInterventionData.tsx
app/containers/ClearInterventionData/utils.ts
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageAttachment/index.tsx
app/global/constants/regex.js
app/global/i18n/globalMessages.js
app/global/reducers/intervention/actions.js
app/global/reducers/intervention/sagas/clearInterventionData.ts
app/utils/validators/numericValidator.ts

- [CIAS-3590](https://htdevelopers.atlassian.net/browse/CIAS30-3590)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/f388811e-48bc-404a-a95d-ece199002c26

[CIAS30-3590] Let researcher decide on data clearance delay

---

app/components/FileUpload/index.tsx
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageAttachment/index.tsx
app/utils/formatters/fileFormatters.ts

- [CIAS-3598](https://htdevelopers.atlassian.net/browse/CIAS30-3598)
- as title

[CIAS30-3598] Filter nulls in file input accepted formats

---

app/components/Input/SearchInput.js
app/components/Input/tests/__snapshots__/index.test.js.snap
app/containers/App/tests/__snapshots__/index.test.js.snap
app/containers/InterventionPage/StarredFilter.tsx
app/containers/InterventionPage/index.js
app/containers/InterventionPage/messages.js
app/containers/InterventionPage/tests/__snapshots__/index.test.js.snap
app/containers/TeamsList/index.js
app/containers/TeamsList/tests/__snapshots__/index.test.js.snap
app/containers/UserList/index.js
app/containers/UserList/messages.js
app/containers/UserList/tests/__snapshots__/index.test.js.snap

- [CIAS-3575](https://htdevelopers.atlassian.net/browse/CIAS30-3575)
- refactor and style search input
- add star filter
https://github.com/Michigan-State-University/cias-web/assets/86963976/db9d2353-231c-4e7a-ab3f-ae4ddafd1abb

[CIAS30-3575] Filter interventions by stars

---

app/containers/InterventionDetailsPage/components/InterventionStatusButtons/tests/index.test.js
app/containers/InterventionPage/index.js
app/containers/InterventionPage/tests/index.test.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/containers/OrganizationInterventionRow/index.js
app/global/reducers/interventions/actions.js
app/global/reducers/interventions/constants.ts
app/global/reducers/interventions/index.js
app/global/reducers/interventions/reducer.js
app/global/reducers/interventions/sagas/fetchInterventions.js
app/global/reducers/interventions/selectors.js
app/models/Status/StatusTypes.js

- [CIAS-3652](https://htdevelopers.atlassian.net/browse/CIAS30-3652)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/19841296-b70b-4922-9869-1d9623ee2d40

[CIAS30-3652] Save intervention list filters when changing page

---

app/containers/LiveChatParticipantPanel/containers/NarratorUnavailableDialog.tsx
app/containers/LiveChatParticipantPanel/messages.ts
app/models/NavigatorSetup/NavigatorSetup.ts

- [CIAS-3593](https://htdevelopers.atlassian.net/browse/CIAS30-3593)
- as title + hide call out instruction for everyone
https://github.com/Michigan-State-University/cias-web/assets/86963976/8e8052f2-0ff0-4f57-92d9-ceb41fb71beb

[CIAS30-3593] Hide call out navigator button if there aren't any navigators added

---

app/components/OriginalTextHover/index.tsx
app/containers/Sessions/components/QuestionData/ThirdPartyQuestion/RecipientsChooser/RecipientsChooser.tsx
app/containers/Sessions/components/QuestionData/ThirdPartyQuestion/ThirdPartyQuestionAnswer.tsx
app/containers/Sessions/components/QuestionData/ThirdPartyQuestion/index.js
app/containers/Sessions/components/QuestionData/ThirdPartyQuestion/reducer.js

- [CIAS-3628](https://htdevelopers.atlassian.net/browse/CIAS30-3628)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/ab72834b-22bf-4b69-8eac-4adcdaf804b6

[CIAS30-3628] Fix saving answer changes on third party question

---

app/containers/ReportingDashboardPage/containers/DashboardSetup/components/ChartSettingsTopSection.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/messages.js

- [CIAS-3630](https://htdevelopers.atlassian.net/browse/CIAS30-3630)
- as title

[CIAS30-3630] Remove redundant chart start collecting data tooltip

---

app/containers/ReportingDashboardPage/containers/DashboardSetup/components/BarChart.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/components/BarChartSettings.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/components/ChartSettings.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/components/ChartTileUI.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/generateBarChartData.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/messages.js
app/global/reducers/dashboardSections/sagas/addChart.js
app/models/Chart/ChartIntervalType.ts
app/models/Chart/index.ts

- [CIAS-3609](https://htdevelopers.atlassian.net/browse/CIAS30-3609)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/053df221-39f6-492d-bea5-275753aed03f

[CIAS30-3609] Add quarter bar charts

---

app/components/DateRangeChooser/DateRangeChooser.tsx
app/components/DateRangeChooser/index.ts
app/components/DateRangeChooser/messages.ts
app/containers/ReportingDashboardPage/containers/DashboardSetup/components/ChartSettings.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/components/PieChartSettings.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/messages.js
app/containers/ReportingDashboardPage/containers/DashboardSetup/styled.js
app/containers/Sessions/components/QuestionData/TlfbConfig/index.tsx
app/containers/Sessions/components/QuestionData/TlfbConfig/messages.ts

- [CIAS-3606](https://htdevelopers.atlassian.net/browse/CIAS30-3606)
- as title

[CIAS30-3606] Add date range inputs to pie charts

---

app/containers/RegisterPage/index.js

- [CIAS-3662](https://htdevelopers.atlassian.net/browse/CIAS30-3662)
- as title
N/A

[CIAS30-3662] Pass cid param when redirecting from register page

---

app/components/AppRoute/index.js

- [CIAS-3669](https://htdevelopers.atlassian.net/browse/CIAS30-3669)
- as title
N/A

[CIAS30-3669] Fix passing query params from AppRoute

---

app/containers/UserInterventionPage/UserSessionTile.tsx
app/containers/UserInterventionPage/index.tsx
app/models/UserIntervention/UserIntervention.ts

- [CIAS-3670](https://htdevelopers.atlassian.net/browse/CIAS30-3670)
- Include health_clinic_id when redirecting to fill session from dashboard
N/A

[CIAS30-3670]  Include health_clinic_id when redirecting to fill session from dashboard

---

app/containers/App/index.js
app/containers/ForbiddenPage/messages.js
app/containers/ForbiddenPage/tests/__snapshots__/index.test.js.snap
app/containers/VerifyUserKeyPage/Loadable.ts
app/containers/VerifyUserKeyPage/index.tsx
app/global/constants/router.ts
app/global/reducers/auth/actions.js
app/global/reducers/auth/constants.js
app/global/reducers/auth/index.js
app/global/reducers/auth/reducer.js
app/global/reducers/auth/sagas/index.js
app/global/reducers/auth/sagas/verifyUserKey.ts
app/global/reducers/auth/types.ts
app/global/types/locationState.ts

- [CIAS-3647](https://htdevelopers.atlassian.net/browse/CIAS30-3647)
- add page for verifying user key and redirect to a proper page after key verification
- change default error title on forbidden page
N/A

[CIAS30-3647] Verify predefined user key

---

app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/ReportTemplateMainSettings.js
app/global/i18n/globalMessages.js

- [CIAS-3659](https://htdevelopers.atlassian.net/browse/CIAS30-3659)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/e8c09d37-7efe-4fcc-84ea-c7152e279134

[CIAS30-3659] Make cover page description input resize to its content

---

app/containers/AnswerSessionPage/components/TextBoxQuestion.js

- [CIAS-3673](https://htdevelopers.atlassian.net/browse/CIAS30-3673)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/0c3960aa-766f-4d19-93eb-ee0c383b8129

[CIAS30-3673] Handle empty answer on free response screen

---

app/containers/AnswerSessionPage/components/MultipleQuestion.js

- [CIAS-3668](https://htdevelopers.atlassian.net/browse/CIAS30-3668)
- when unchecking answer on multiple answer question screen, compare answers by variables, not by variables values
N/A

[CIAS30-3668] Fix unchecking answer in multiple answer question

---

app/global/reducers/auth/sagas/verifyUserKey.ts
app/global/reducers/auth/types.ts
app/models/Api/Data.ts
app/utils/mapResponseObjects.js

- [CIAS-3693](https://htdevelopers.atlassian.net/browse/CIAS30-3693)
- as title
N/A

[CIAS30-3693] Adjust FE to BE changes in verifying predefined participants

---

app/components/AppRoute/index.js
app/containers/AnswerSessionPage/index.js
app/global/constants/router.ts
app/global/reducers/auth/constants.js
app/global/reducers/auth/sagas/logIn.js
app/global/reducers/auth/sagas/logOut.js
app/utils/axios.js
app/utils/router/getRedirectPathFromQueryParams.ts
app/utils/router/index.ts

- [CIAS-3702](https://htdevelopers.atlassian.net/browse/CIAS30-3702)
- [CIAS-3706](https://htdevelopers.atlassian.net/browse/CIAS30-3706)
- create function handling other query params when redirecting using `redirect_to` query param
https://github.com/Michigan-State-University/cias-web/assets/86963976/da600d60-4baf-461a-ae8e-1b859f2304d5

[CIAS30-3702][CIAS30-3706] Fix passing query params when redirecting from login page

---

app/containers/AnswerSessionPage/layouts/SingleQuestionLayout.js

- [CIAS-3712](https://htdevelopers.atlassian.net/browse/CIAS30-3712)
- as title
N/A

[CIAS30-3712] Prevent submitting single answer twice

---

app/containers/App/tests/__snapshots__/index.test.js.snap
app/containers/InterventionPage/index.js
app/containers/InterventionPage/tests/__snapshots__/index.test.js.snap

TEST => DEV 21/09/2023

---

app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/ReportTemplateMainSettings.js

- [CIAS-3717](https://htdevelopers.atlassian.net/browse/CIAS30-3717)
- as title

[CIAS30-3717] Disable cover letter switch for published interventions

---

app/containers/AnswerSessionPage/layouts/FinishScreenLayout.tsx
app/containers/InterventionDetailsPage/containers/ParticipantInviter/HealthClinicCollapse.tsx
app/containers/InterventionDetailsPage/containers/ParticipantInviter/InviteEmailParticipantsForm.tsx
app/containers/InterventionDetailsPage/containers/ParticipantInviter/InviteEmailParticipantsView.tsx
app/containers/InterventionDetailsPage/containers/ParticipantInviter/SelectSessionControls.tsx
app/containers/InterventionDetailsPage/containers/ParticipantInviter/UploadEmailsView.tsx
app/containers/InterventionDetailsPage/containers/ParticipantInviter/messages.ts
app/containers/InterventionDetailsPage/containers/ParticipantInviter/types.ts
app/containers/InterventionDetailsPage/containers/ParticipantInviter/utils.ts

- [CIAS-3727](https://htdevelopers.atlassian.net/browse/CIAS30-3727)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/c61aa478-b7b3-4ce5-85ed-cb01162c3d96

[CIAS30-3727] Add switch for selecting first session as intervention starting point

---

app/containers/AnswerSessionPage/layouts/FinishScreenLayout.tsx
app/containers/App/index.js
app/containers/Navbar/index.js
app/containers/Navbar/messages.ts
app/containers/Sidebar/components/DefaultSidebar.js
app/containers/Sidebar/index.js
app/containers/Sidebar/tests/__snapshots__/index.test.js.snap
app/containers/Sidebar/tests/index.test.js
app/containers/UserInterventionPage/index.tsx
app/models/User/RolesManager/UserRoles.ts

- [CIAS-3705](https://htdevelopers.atlassian.net/browse/CIAS30-3705)
- remove limitation for predefined participant to go to `/` path
- format predefined participant name in navbar (My account)
- show default navbar on user intervention page
- don't show sidebar if it would be empty
N/A

[CIAS30-3705] Allow predefined participant to see intervention list

---

app/containers/AnswerSessionPage/messages.js
app/containers/AnswerSessionPage/saga.js

- [CIAS-3743](https://htdevelopers.atlassian.net/browse/CIAS30-3743)
- display submit answer error message from BE

[CIAS30-3743] Format submit answer error

---

app/containers/Navbar/index.js
app/global/reducers/auth/sagas/verifyUserKey.ts

- [CIAS-3742](https://htdevelopers.atlassian.net/browse/CIAS30-3742)
- as title + format name displayed in navbar
N/A

[CIAS30-3742] Clear headers before verifying predefined participant link

---

app/containers/InterventionDetailsPage/containers/ParticipantInviter/ManagePredefinedParticipantView.tsx

- [CIAS-3746](https://htdevelopers.atlassian.net/browse/CIAS30-3746)
- as title

[CIAS30-3746] Disable send SMS invitation button if participant is deactivated

---

app/containers/InterventionDetailsPage/containers/ParticipantInviter/EmailParticipantsTableRow.tsx

- [CIAS-3749](https://htdevelopers.atlassian.net/browse/CIAS30-3749)
- do not show duplicated targets on invitation list
N/A

[CIAS30-3749] Handle duplicated invitations

---

app/containers/AnswerSessionPage/index.js
app/containers/AnswerSessionPage/layouts/FinishScreenLayout.tsx
app/containers/AnswerSessionPage/saga.js
app/containers/InterventionDetailsPage/Header.js
app/global/reducers/intervention/reducer.js

- [CIAS-3771](https://htdevelopers.atlassian.net/browse/CIAS30-3771)
- added checks to prevent resending requests at answer session page after app language name
N/A

[CIAS30-3771] Fix doubled requests when starting session in RTL language

---

app/containers/ClearInterventionData/ClearInterventionDataModalContent.tsx
app/containers/ClearInterventionData/messages.ts

- [CIAS-3718](https://htdevelopers.atlassian.net/browse/CIAS30-3718)
- as title
https://github.com/Michigan-State-University/cias-web/assets/86963976/2458c250-786f-496d-91da-cafe15a322bd

[CIAS30-3718] Add confirmation step to clear intervention data

---

app/containers/InterventionDetailsPage/Header.js
app/containers/InterventionDetailsPage/components/InterventionStatusButtons/CsvButtons.js
app/containers/InterventionDetailsPage/components/InterventionStatusButtons/index.js
app/containers/InterventionDetailsPage/index.js
app/containers/Sessions/components/QuestionDetails/index.tsx
app/containers/SettingsPanel/containers/ConversationsTranscriptPanel.tsx
app/containers/SettingsPanel/containers/LogoUpload.js
app/containers/SettingsPanel/index.tsx
app/global/reducers/intervention/actions.js
app/global/reducers/intervention/reducer.js
app/global/reducers/intervention/sagas/interventionLogo.js
app/models/Intervention/Intervention.ts

- [CIAS-3800](https://htdevelopers.atlassian.net/browse/CIAS30-3800)
- as title
N/A

[CIAS30-3800] Adjust FE to new intervention files structure

---

app/containers/InterventionDetailsPage/Header.js

- [CIAS-3816](https://htdevelopers.atlassian.net/browse/CIAS30-3816)
- as title

[CIAS30-3816] Change export answer button to secondary

---

app/components/ExportModal/ExportedFilePanel.tsx
app/components/ExportModal/messages.ts
app/translations/en.json

- [CIAS-3836](https://htdevelopers.atlassian.net/browse/CIAS30-3836)
- update re-export intervention and answers buttons positions and labels
N/A

[CIAS30-3836] Update export buttons

---

app/containers/AnswerSessionPage/layouts/HenryFordInitialScreenLayout.tsx
app/models/HfhsPatient/HfhsPatient.ts

- [CIAS-3848](https://htdevelopers.atlassian.net/browse/CIAS30-3848)
- as title
N/A

[CIAS30-3848] Make all HF initial screen fields optional

---

app/components/Tabs/index.js
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/HfHsAccessModalUI.tsx
app/containers/InterventionDetailsPage/components/Modals/ThirdPartyToolsAccessModal/ThirdPartyToolsAccessModal.tsx
app/containers/InterventionDetailsPage/index.js

- [CIAS-3860](https://htdevelopers.atlassian.net/browse/CIAS30-3860)
- Third party tools modal with Henry Ford tab to the researcher if HF access is enabled
N/A

[CIAS30-3860] Allow researcher to change selected HF clinic locations

---

app/components/FormikDatePicker/index.tsx
app/components/Input/ApprovableInput.js

- [CIAS-3520](https://htdevelopers.atlassian.net/browse/CIAS30-3520)
- as title
N/A

[CIAS30-3520] Validate date format strictly

---

app/containers/AnswerSessionPage/index.js
app/containers/AnswerSessionPage/layouts/CurrencyQuestionLayout.js

- [CIAS-3699](https://htdevelopers.atlassian.net/browse/CIAS30-3699)
- disable continue button on currency screen unless valid amount is provided
N/A

[CIAS30-3699] Handle required currency question

---

app/containers/AnswerSessionPage/layouts/HenryFordInitialScreenLayout.tsx
app/models/HfhsPatient/HfhsPatient.ts

TEST => DEV 21/12/2023

---

app/containers/App/tests/__snapshots__/index.test.js.snap
app/containers/Navbar/components/messages.js
app/translations/en.json

- [CIAS-3885](https://htdevelopers.atlassian.net/browse/CIAS30-3885)
- change resources button title from "Resources" to "Support"

[CIAS30-3885] Update resources link copy

---

.github/CODEOWNERS

Test removing codeowners file for requiring approve from admins not codeowners

Test removing codeowners file

---

app/containers/AnswerSessionPage/components/PhoneQuestion.js

- [CIAS30-3913](https://htdevelopers.atlassian.net/browse/CIAS30-3913)
- 
N/A

[CIAS30-3913] Update phone confirmation when user phone changes

---

app/containers/AnswerSessionPage/index.js

Hotfix: modified canSkipNarrator logic on AnswerSessionPage

---

app/containers/AnswerSessionPage/index.js
app/utils/animationsHelpers/useAudioHelper.ts

Cias30 3559 hotfix

---

app/containers/AnswerSessionPage/index.js

CIAS30-3559: adjusted formula reflection type

---

app/utils/animationsHelpers/useAudioHelper.ts

- Omit non-readable sentences
N/A

CIAS30 IOS/Safari error

---

app/containers/AnswerSessionPage/index.js
app/containers/AnswerSessionPage/selectors.js
app/global/reducers/globalState/selectors.js

TRANSLATION_ISSUE_FIX: added language based on question

---

app/containers/AnswerSessionPage/index.js

CIAS30-3926-narrator-issue-on-ios

---

app/containers/AnswerSessionPage/index.js

CIAS30-3926: added one more contidion

---

app/containers/AnswerSessionPage/index.js

dev -> test 28/08

---

app/global/constants/regex.js
app/global/reducers/intervention/sagas/createSession.js
app/global/reducers/session/messages.js
app/global/reducers/session/sagas/bulkEditSession.js

Sms changes requested by client

---

app/components/Input/styled.js
app/components/Input/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionData/MultiQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionData/SingleQuestion/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionDetails/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionSubtitle/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/components/QuestionTitle/tests/__snapshots__/index.test.js.snap
app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/SectionCaseItem.js
app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/TemplateSectionItem.js
app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/TemplateSectionSettings.js
app/containers/SettingsPanel/tests/__snapshots__/index.test.js.snap

- [CIAS-3940](https://htdevelopers.atlassian.net/browse/CIAS30-3940)
- 
N/A

[CIAS30-3940] Add rich text to report templates

---

app/containers/Sessions/containers/TextMessagesPage/components/TextMessageScheduling/index.js
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageScheduling/messages.js
app/containers/Sessions/containers/TextMessagesPage/components/TextMessageScheduling/textMessageScheduleOptionsMessages.ts
app/containers/Sessions/containers/TextMessagesPage/containers/TextMessageSettings/index.js
app/containers/Sessions/containers/TextMessagesPage/containers/TextMessageTitles/index.js
app/containers/Sessions/containers/TextMessagesPage/containers/TextMessageTitles/textMessageScheduleOptionsMessages.ts
app/containers/Sessions/containers/TextMessagesPage/index.js
app/global/reducers/textMessages/index.js
app/global/reducers/textMessages/settings/actions.js
app/global/reducers/textMessages/settings/constants.js
app/global/reducers/textMessages/settings/reducer.js
app/models/TextMessage/TextMessageScheduleOption.ts

CIAS30-3941: ability to send sms after user defined time

---

app/containers/AnswerSessionPage/layouts/FinishScreenLayout.tsx
app/containers/App/index.js
app/containers/SettingsPanel/index.tsx
app/containers/UserInterventionPage/index.tsx

CIAS30-3939: added ability to share flexible modular intervention to anyone with the link

---

app/containers/Sessions/containers/SettingsSessionPage/components/SessionSettings.js
app/containers/Sessions/containers/SettingsSessionPage/components/messages.js
app/translations/ar.json
app/translations/en.json
app/translations/es.json

MISSING-TOOLTIP: added missing sms code tooltip

---

app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/ReportTemplatePreview.js

- [CIAS30-3942](https://htdevelopers.atlassian.net/browse/CIAS30-3942)
- 
N/A

[CIAS30-3942] Adjust Report summary to use rich text

---

app/components/QuickExit/index.tsx

CIAS30-QUICK_EXIT_SUPPRESSION show modal on quick exit only once

---

app/global/reducers/textMessages/settings/reducer.js

CIAS30-3941: fixed badly working reducer

---

app/containers/Sessions/containers/SettingsSessionPage/components/messages.js
app/global/reducers/intervention/sagas/createSession.js
app/translations/en.json

FIXES: changed translations for default sms campaign values

---

app/components/Player/index.tsx
app/containers/AnswerSessionPage/actions.js
app/containers/AnswerSessionPage/constants.js
app/containers/AnswerSessionPage/index.js
app/containers/AnswerSessionPage/layouts/CommonLayout.js
app/containers/AnswerSessionPage/reducer.js
app/containers/AnswerSessionPage/saga.js
app/containers/AnswerSessionPage/selectors.js

VIDEO_TRACKING: ability to track video statisics

---

app/components/Player/index.tsx

VIDEO_TRACKING: typescriopt fix

---

app/components/Player/index.tsx

dev -> test 11.10 2

---

.github/workflows/main.yml

Update cache action to v4 in CI workflow

---

app/components/IdleTimer/constants.js
app/components/IdleTimer/index.js
app/utils/useConversationChannel/useConversationChannel.ts

- [CIAS30-3987](https://htdhealth.atlassian.net/browse/CIAS30-3987)
- 
N/A

[CIAS30-3987] Add activity events for idle timer and implement user activity ping

---

app/components/Modal/Modal.tsx

[GWDG] Pop-up boxes close without data saving if you click outside of the pop-up window and data is lost
- [CIAS-3931](https://htdhealth.atlassian.net/browse/CIAS30-3931)
- 
N/A

[CIAS30-3931] Pop-up boxes close without data saving if you click outside of the pop-up window and data is lost
